### ISSUE TITLE
不能设置tab选中状态时的背景色么，同时带有indicator？

### ISSUE THREAD

**Issue by wangzhongITger** [qstumn/VerticalTabLayout#17]
如题，好像没有这个功能是么，只有自定义indicator

**Comment by wangzhongITger** [comment]
而且也只有左右布满三种样式无法更深的自定义

**Comment by qstumn** [comment]
https://github.com/qstumn/VerticalTabLayout#一些特性 Tab支持android:state_selected
indicator 暂时只有三种样式
