### ISSUE TITLE
修改TabLayout数量时app出现闪退的问题

### ISSUE THREAD

**Issue by ThinkmanWang** [qstumn/VerticalTabLayout#2]
你好，TabLayout用着非常喜欢，我在平时的项目中一直有使用。

使用中发现一个粗心导致的小失误。
在 VerticalTabLayout:removeAllTabs()方法里。

for (int i = 0; i < mTabStrip.getChildCount(); i--) {
    mTabStrip.removeViewAt(i);
}

应该修改为 
for (int i = 0; i < mTabStrip.getChildCount(); i++) {
    mTabStrip.removeViewAt(i);
}

不然在调用removeAllTabs()的时候会出现数组越界的问题。

**Comment by ThinkmanWang** [comment]
不好意思更正一下，应该改为：
while(mTabStrip.getChildCount() > 0) {
    mTabStrip.removeViewAt(0);
 }

mSelectedTab = null;

原先的代码永远无法removeAll
举例：
初始的时候mTabStrip.getChildCount() 为 2
一次循环后：
i==1
mTabStrip.getChildCount() == 1
这个时候因为 i < mTabStrip.getChildCount() 的条件无法满足，所以剩下的tab不会再被移除

**Comment by qstumn** [comment]
谢谢您的提醒，这我写的不对，之前的确没在意
