### ISSUE TITLE
动态刷新支持吗

### ISSUE THREAD

**Issue by bruceyu1994** [qstumn/VerticalTabLayout#3]
如何adapter中的数据变了，tab项如何动态刷新？ @qstumn

**Comment by qstumn** [comment]
您好，如果是结合ViewPager并调用了setupWithViewPager的话，是可以动态刷新的，adapter.notifyDataSetChanged即可，如果是单独使用TabAdapter就没办法了，可以重新setTabAdapter来进行刷新
