### ISSUE TITLE
怎么修改Indicator高度

### ISSUE THREAD

**Issue by huyubao** [qstumn/VerticalTabLayout#30]

**Comment by huyubao** [comment]
已经解决

**Comment by Rudra-n-khatri** [comment]
@huyubao  Can you help me with this, i have the same issue i want to reduce the height of strip. I prefer small circular dot instead of a line. Can you please tell me how you did it ?

**Comment by huyubao** [comment]
Modify source code

**Comment by Rudra-n-khatri** [comment]
Thanks for replying, but that's a lot of code to go through. I have tried making some changes but it's not working for me.  Can you share some code that will be a great help?

**Comment by Rabbit95** [comment]
请问怎么修改指示器的高度。
