### ISSUE TITLE
 tabLayout.setTabSelected(position)时，indicator没有移动

### ISSUE THREAD

**Issue by pngfi** [qstumn/VerticalTabLayout#5]
我使用setupwithFragment方法，然后我在Actvity的onCreate方法中调用tabLayout.setTabSelected(position)。
首先我遇到的第一个问题是fragment 重复添加， 
List<Fragment> addedFragments = mManager.getFragments();
            if ((addedFragments == null || !addedFragments.contains(fragment)) && mContainerResid != 0) {
                ft.add(mContainerResid, fragment);
            }
这里的contains判断似乎并没有用

第二个问题是调用tabLayout.setTabSelected(position) tabview的文字状态改变了，但是indicator并没有移动。

**Comment by qstumn** [comment]
在onCreate中调用setTabSelected的确会造成indicator没有移动，应该是因为这时候indicator的高度还没有测量出来导致移动动画无法正确执行
至于fragment重复添加是指造成了界面上的fragment重叠了么？这个情况我没有测试出来，如果是在系统内存不足导致fragment所在的Activity被杀掉又重启的情况下出现的，这个其实算是Android系统的一个BUG，24.0以上的support包已经修复这个问题。如果不是这样，我猜想可能是因为FragmentTransaction.commit()方法不是立刻执行的，可能此时FragmentManager还没有这个fragment，至于contains判断似乎并没有用这个问题我测试了下是起了作用的，您是在什么情况下出现的这个问题？
非常感谢您能提出宝贵的意见，我已在1.2.1版中对这两个问题进行了修复，您可以看下是否解决了您的问题。

**Comment by liguangze** [comment]
@qstumn  我还是有这个问题啊 indicator没有移动
