### ISSUE TITLE
TabAdapter中设置getBackground(int position)无效

### ISSUE THREAD

**Issue by PontonMao** [qstumn/VerticalTabLayout#6]
@qstumn 
我的TabItem背景文件：drawable/tab_item_bg_selector.xml

<
?
xml version="1.0" encoding="utf-8"?>

> <selector

 xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:drawable="@color/colorAccent" android:state_selected="true"/>

    <item android:drawable="@color/colorAccent" android:state_pressed="true"/>

    <item android:drawable="@color/colorWhite"/>

> </
selector>

在class MyTabAdapter implements TabAdapter {

        ...

        @Override
        public int getBackground(int position) {
            return R.drawable.tab_item_bg_selector;
        }
}
设置无效，这个是因为什么？

**Comment by qstumn** [comment]
抱歉，暂不支持android:state_selected

**Comment by qstumn** [comment]
您好，已更新1.2.2添加android:state_selected支持   https://github.com/qstumn/VerticalTabLayout/releases/tag/1.2.2
