### ISSUE TITLE
几点问题，谢谢

### ISSUE THREAD

**Issue by coolmaye** [qstumn/VerticalTabLayout#8]
你用setmargin的方式，用户会经常点不到相应的tab，这样体验很差，直接更改为增加tab的height不可以吗，还有水波纹效果可以去掉吗？配合fill属性真的挺丑的  ，还有 现在的样式会包含 左侧indicater和fill的indicater，应该在多一种属性，将两个结合起来的，因为这是一种流行样式

**Comment by qstumn** [comment]
你好，感谢你的反馈，Margin本身就是外边距，和Height是不一样的。如果需要增加高度，本身就有setTabHeight可供使用，水波纹是默认的点击效果，当然可以去掉，setBackground传null或者负数即可，注释中有说明。
另外两个结合起来是什么效果呢？能否说的具体点，抱歉我没理解出来。

**Comment by coolmaye** [comment]
我看了你的源码，如果是fix模式的，直接忽略tabheight，如果是另外一个模式的，固定添加margin，改都改不了，不过确height确实有用了。我想实现一个点击后那一片tab可以跟着变色的需求，而且indicater也还要有。不过最后用recycleView做了。

**Comment by qstumn** [comment]
fix模式是尽量让所有tab都均分VerticalTabLayout的所有高度，scrollable模式tab高度是wrap_content，你可以使用setTabHeight更改所有tab的高度，也可以get到某个tab设置其高度，至于你说的固定添加margin，改都改不了，很抱歉我没理解是什么意思？
你说的点击一个tab跟着变色是不是指tab背景色改变，setBackground传一个selector即可，支持android:state_selected。

**Comment by a458167371** [comment]
fix模式  想修改Tab的高度和margin  都不起作用  xml文件和代码设置都不起作用

**Comment by qstumn** [comment]
fix顾名思义就是让所有tab充满VerticalTabLayout均分其高度，Tab高度和margin当然会不起作用了
如果需要自定义Tab高度、margin请用scrollable
